[day]
100 = 'sun'
101 = 'half sun cloud'
102 = 'qurt sun rain'
103 = 'half sun rain'
104 = 'qurt sun snow'
105 = 'half sun snow'
111 = 'then sun cloud'
114 = 'then sun rain'
117 = 'then sun snow'
119 = 'then sun rain_thunder'
140 = 'half sun rain_thunder'
149 = 'then sun snow_thunder'
150 = 'half sun snow_thunder'
156 = 'half sun raincloud'
158 = 'half sun raincloud_thunder'
166 = 'then sun raincloud'
168 = 'then sun raincloud_thunder'
200 = 'cloud'
201 = 'half cloud sun'
202 = 'qurt raincloud rain'
203 = 'half raincloud rain'
204 = 'qurt raincloud snow'
205 = 'half raincloud snow'
211 = 'then cloud sun'
214 = 'then raincloud rain'
217 = 'then raincloud snow'
219 = 'then raincloud rain_thunder'
240 = 'half raincloud rain_thunder'
249 = 'then raincloud snow_thunder'
250 = 'half raincloud snow_thunder'
255 = 'raincloud'
256 = 'half raincloud sun'
257 = 'raincloud_thunder'
258 = 'half raincloud_thunder sun'
266 = 'then raincloud sun'
268 = 'then raincloud_thunder sun'
300 = 'rain'
301 = 'half rain sun'
302 = 'half rain raincloud'
311 = 'then rain sun'
313 = 'then rain raincloud'
315 = 'then rain snow'
330 = 'half rain snow'
341 = 'then rain_thunder sun'
343 = 'then rain_thunder raincloud'
345 = 'then rain_thunder snow'
350 = 'rain_thunder'
400 = 'snow'
401 = 'half snow sun'
402 = 'half snow raincloud'
411 = 'then snow sun'
413 = 'then snow raincloud'
414 = 'then snow rain'
441 = 'then snow_thunder sun'
443 = 'then snow_thunder raincloud'
444 = 'then snow_thunder rain'
450 = 'snow_thunder'
500 = 'heavyrain'
550 = 'heavyrain_thunder'
600 = 'heavysnow'
650 = 'heavysnow_thunder'
700 = 'windrain'
750 = 'windrain_thunder'
800 = 'windsnow'
850 = 'windsnow_thunder'
999 = 'unknown'

[night]
100 = 'moon'
101 = 'half moon cloud'
102 = 'qurt moon rain'
103 = 'half moon rain'
104 = 'qurt moon snow'
105 = 'half moon snow'
111 = 'then moon cloud'
114 = 'then moon rain'
117 = 'then moon snow'
119 = 'then moon rain_thunder'
140 = 'half moon rain_thunder'
149 = 'then moon snow_thunder'
150 = 'half moon snow_thunder'
156 = 'half moon raincloud'
158 = 'half moon raincloud_thunder'
166 = 'then moon raincloud'
168 = 'then moon raincloud_thunder'
200 = 'cloud'
201 = 'half cloud moon'
202 = 'qurt raincloud rain'
203 = 'half raincloud rain'
204 = 'qurt raincloud snow'
205 = 'half raincloud snow'
211 = 'then cloud moon'
214 = 'then raincloud rain'
217 = 'then raincloud snow'
219 = 'then raincloud rain_thunder'
240 = 'half raincloud rain_thunder'
249 = 'then raincloud snow_thunder'
250 = 'half raincloud snow_thunder'
255 = 'raincloud'
256 = 'half raincloud moon'
257 = 'raincloud_thunder'
258 = 'half raincloud_thunder moon'
266 = 'then raincloud moon'
268 = 'then raincloud_thunder moon'
300 = 'rain'
301 = 'half rain moon'
302 = 'half rain raincloud'
311 = 'then rain moon'
313 = 'then rain raincloud'
315 = 'then rain snow'
330 = 'half rain snow'
341 = 'then rain_thunder moon'
343 = 'then rain_thunder raincloud'
345 = 'then rain_thunder snow'
350 = 'rain_thunder'
400 = 'snow'
401 = 'half snow moon'
402 = 'half snow raincloud'
411 = 'then snow moon'
413 = 'then snow raincloud'
414 = 'then snow rain'
441 = 'then snow_thunder moon'
443 = 'then snow_thunder raincloud'
444 = 'then snow_thunder rain'
450 = 'snow_thunder'
500 = 'heavyrain'
550 = 'heavyrain_thunder'
600 = 'heavysnow'
650 = 'heavysnow_thunder'
700 = 'windrain'
750 = 'windrain_thunder'
800 = 'windsnow'
850 = 'windsnow_thunder'
999 = 'unknown'
